"""propkb.store -- deterministic plumbing for the per-property knowledge base.

Scaffold a property, file an artifact, (re)index, list. NOTHING smart lives here:
classification, fact extraction, and regenerating UNDERSTANDING/PLAN are Claude's
job via the /intake skill. Property corpora live under ``properties/<slug>/`` and
are indexed by the docrag engine pointed at the property instance (see settings).
"""

from __future__ import annotations

import os
import shutil
from datetime import date

from . import settings

KINDS = ("docs", "emails", "gis", "web", "photos")


# ---------- paths ----------

def prop_dir(slug: str) -> str:
    return os.path.join(settings.properties_root(), slug.strip().lower())


def paths(slug: str) -> dict:
    base = prop_dir(slug)
    return {
        "slug": slug.strip().lower(),
        "dir": base,
        "facts": os.path.join(base, "facts.yaml"),
        "timeline": os.path.join(base, "timeline.md"),
        "understanding": os.path.join(base, "UNDERSTANDING.md"),
        "plan": os.path.join(base, "PLAN.md"),
        "sources": os.path.join(base, "sources"),
        **{k: os.path.join(base, "sources", k) for k in KINDS},
    }


def list_properties() -> list[str]:
    root = settings.properties_root()
    if not os.path.isdir(root):
        return []
    out = []
    for name in sorted(os.listdir(root)):
        if name.startswith(".") or name.startswith("_"):
            continue
        if os.path.isdir(os.path.join(root, name)):
            out.append(name)
    return out


# ---------- scaffold ----------

_FACTS_STUB = """\
# Structured facts for {address}.
# Canonical, queryable layer. Each non-obvious fact carries a `src: [T-NN]`
# pointing to a timeline.md entry. Maintained by /intake. Created: {today}.

property:
  slug: {slug}
  address: {address}
  status: new
"""

_TIMELINE_STUB = """\
# Timeline -- {address} (the provenance chain)

Dated, append-only record of every fact, document, and conversation, with its
source. facts.yaml and UNDERSTANDING.md cite these IDs (T-NN). New entries go at
the bottom via /intake.

---

**T-01 - {today} - Property created**
Knowledge base scaffolded for {address}.
"""

_UNDERSTANDING_STUB = """\
# CURRENT UNDERSTANDING -- {address}

> Living synthesis of everything known about this property. Regenerated by
> /intake whenever new info lands. Claims cite timeline.md (T-NN).
> **Last updated: {today}** - Status: new - Confidence: low

## 1. Snapshot
_(intake will fill this in)_

## 7. Open questions
- [ ] (none yet)

> Research, not legal/engineering advice.
"""

_PLAN_STUB = """\
# CURRENT PLAN -- {address}

> Development concept + business projection + decision gates. Distinct from
> UNDERSTANDING.md (what IS) -- this is what we WANT and whether it pencils.
> **Last updated: {today}** - Stage: pre-acquisition

## Development concept
_(to be defined)_

## Next actions (live)
1. [ ] Define development concept.
"""


def create(slug: str, address: str) -> dict:
    """Scaffold a property KB. Idempotent: never clobbers existing files."""
    p = paths(slug)
    os.makedirs(p["dir"], exist_ok=True)
    for k in KINDS:
        os.makedirs(p[k], exist_ok=True)
    ctx = {"address": address or p["slug"], "slug": p["slug"],
           "today": date.today().isoformat()}
    for key, stub in (("facts", _FACTS_STUB), ("timeline", _TIMELINE_STUB),
                      ("understanding", _UNDERSTANDING_STUB), ("plan", _PLAN_STUB)):
        if not os.path.exists(p[key]):
            with open(p[key], "w", encoding="utf-8") as f:
                f.write(stub.format(**ctx))
    return p


# ---------- ingest ----------

def ingest(slug: str, file: str, kind: str = "docs", rename: str | None = None) -> str:
    """Copy an artifact into sources/<kind>/. Returns the destination path."""
    if kind not in KINDS:
        raise ValueError("kind must be one of %s" % (KINDS,))
    src = os.path.abspath(os.path.expanduser(file))
    if not os.path.isfile(src):
        raise FileNotFoundError(src)
    dest_dir = paths(slug)[kind]
    os.makedirs(dest_dir, exist_ok=True)
    dest = os.path.join(dest_dir, rename or os.path.basename(src))
    shutil.copy2(src, dest)
    return dest


def write_text(slug: str, text: str, name: str, kind: str = "docs") -> str:
    """Persist pasted/extracted text (e.g. OCR sidecar, parsed email) as a file
    under sources/<kind>/ so it gets indexed. Returns the path."""
    if kind not in KINDS:
        raise ValueError("kind must be one of %s" % (KINDS,))
    dest_dir = paths(slug)[kind]
    os.makedirs(dest_dir, exist_ok=True)
    dest = os.path.join(dest_dir, name)
    with open(dest, "w", encoding="utf-8") as f:
        f.write(text)
    return dest


# ---------- index ----------

def reindex(slug: str, full: bool = False) -> int:
    """(Re)build the property's corpus via the docrag engine, bound to the
    property instance. Incremental by SHA256 unless full."""
    settings.apply_docrag_env()
    from docrag import index as _index  # imported AFTER env is applied
    argv = ["build", "--corpus", slug.strip().lower(), "--confirm"]
    if full:
        argv.append("--full")
    return _index.main(argv)
